javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
stylesheets:
  app:
    - public/stylesheets/reset.css
    - public/stylesheets/main.css
