package_assets: off
package_path: packages
compressor_options:
  optimize: false

javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/rails.js
    - public/javascripts/socket.io/socket.io.min.js
    - public/javascripts/underscore-min.js
    - public/javascripts/jquery.tipsy.js
    - public/javascripts/application.js
    - public/javascripts/messaging.js
stylesheets:
  app:
    - public/stylesheets/reset.css
    - public/stylesheets/main.css
    - public/stylesheets/tipsy.css
