package_assets: off
package_path: packages
compressor_options:
  optimize: false

javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
stylesheets:
  app:
    - public/stylesheets/reset.css
    - public/stylesheets/main.css
